### ISSUE TITLE
Configure injector via webpack

### ISSUE THREAD

**Issue by NechiK** [lifaon74/ng2-popups#2]
When I use your popup on project with Webpack I see next error

`Error: Uncaught Error: moduleId should be a string in "Ng2ComponentInjectorComponent". See https://goo.gl/wIDDiL for more information.
If you're using Webpack you should inline the template and the styles, see https://goo.gl/X2J8zc. in http://localhost:8080/ at line 170`

How can I fix it ?

**Comment by lifaon74** [comment]
Hum, I'm not an expert with webpack, but if guess module.id is used by commonjs. This was heavily used with ng2. I'm not sure but ng4 seems to have removed this. Could you try https://github.com/lifaon74/ngx-popups ? I created this for ng4.
